/*
 * gsscred-race
 * Brandon Azad
 *
 * Exploit a race condition in the com.apple.GSSCred XPC service.
 */

#ifndef GSSCRED_RACE__GSSCRED_RACE_H_
#define GSSCRED_RACE__GSSCRED_RACE_H_

#include <stdarg.h>
#include <stdbool.h>

// A function to handle log messages generated by gsscred_race. By default messages are printed to
// stderr. Type is one of:
//   - D: Debug
//   - I: Info
//   - W: Warning
//   - E: Error
// Setting this value to NULL will disable logging.
extern void (*gsscred_race_log)(char type, const char *format, va_list ap);

// Run the race condition.
bool gsscred_race(void);

#endif
